### ISSUE TITLE
level 23 :only-of-type

### ISSUE THREAD

**Issue by cd88** [flukeout/restaurant#126]
(Disclaimer: I'll admit I'm actually refreshing my css knowledge with CSS Diner, so I could be wrong about this)

`apple.small:only-of-type` is a correct answer for level 23
...but it isn't the only `apple.small` nor is it the only `plate apple.small:only-of-type`, which also registers as correct

`.small:only-of-type` selects just the second `apple.small` and the `pickle.small`, which doesn't make sense, how could two things both be the only thing. So I'm thinking, "oh, it's somehow already looking inside plate." But should it be?

So now I think `plate apple:only-of-type` should be _the_ correct answer utilizing the introduced selector for the level.

Afterthought: at first glance, `apple.small:only-child` is the most obvious solution for this puzzle

P.S. I wanted to contribute bc I've shared this project so many times and it's helped a lot of people, myself included. Thanks so much. Great work.

**Comment by flukeout** [comment]
hey @c43, just for clarity you're saying that `apple.small:only-of-type` shouldn't be correct because there are two `apple.small` on the table, right?

I believe that `:only-of-type` automatically looks within that elements parent. So in the case of `apple.small:only-of-type` you're basically saying...
- Hey small apples, are you the ONLY apple inside on your parent element (plate)?

The first small apple has a regular apple as a sibling element, so it doesn't qualify, leaving only the small apple. 

I think that the main descriptor of that element is missing that distinction though...

```
Select elements that are the only ones of their type
```

...I'll update it. 

Hope that helps!

**Comment by flukeout** [comment]
MDN explains the selector this way...

`The :only-of-type CSS pseudo-class represents any element that has no siblings of the given type.`

...is that more clear?

**Comment by flukeout** [comment]
Okay, I updated the help text in the game, should be live soon. Thanks for filing & sharing the diner!
