### ISSUE TITLE
Level 19

### ISSUE THREAD

**Issue by deadcoder0904** [flukeout/restaurant#137]
I think its wrong..It works for `bento:nth-child(2)` while it must work for `bento:nth-last-child(2)`; it works for `bento:nth-last-child(3)`

**Comment by deadcoder0904** [comment]
I checked the source code & I think it must be `bento:nth-last-child(2)` [here](https://github.com/flukeout/css-diner/blob/develop/js/levels.js#L396)

**Comment by flukeout** [comment]
Hi @deadcoder0904 - this level gives a lot of people trouble. The correct answer is ``bento::nth-last-child(3)``. To help you see why, first try..

``:nth-last-child(3)``

This selects two elements, the bento and the orange. Both of these are the 3rd last children  (3rd from last) of their parent element.

But since we only want the bento, we need to add that to the selector. We have to say give me the 3rd last child that is ALSO the bento, which looks like...

``bento:nth-last-child(3)``

Let me know if that helps.

**Comment by deadcoder0904** [comment]
Ohhh, I got it thanks :+1: I thought that `bento:nth-last-child(3)` would find only `bento` tags from the parent element, which is not the case
