### ISSUE TITLE
Perhaps an issue with 15

### ISSUE THREAD

**Issue by Stralle** [flukeout/restaurant#198]
Hey,
I'm stuck on 15th question - I should select top orange.
![image](https://user-images.githubusercontent.com/24244340/84798410-38a1c780-affb-11ea-89e6-01c91caeccf3.png)

Am I missing something and this should be a valid solution or what?
System doesn't want to accept my answer :/

Also I even tried div plate:first-child

Thanks!

**Comment by sskorc** [comment]
@Stralle The description might be misleading. I guess [MSDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child) describes it better:

```
/* Selects any <p> that is the first element
   among its siblings */
p:first-child {
  color: lime;
}
```

So you need to use `:first-child` pseudo-selector on the element you want to select (among its siblings), not the parent of that element.

**Comment by aecko-eyes** [comment]
Hi, thanks to you two. I understand with your answer, @sskorc, but I agree with you @Stralle: the orange on the top should be the third (the third to be put)?... I find it more logical with the "cascading style" too, because the last thing you put, takes over the previous ones. Yet, we can see in the css that the first is over the next ones, so it seems to be confusing... (:'

**Comment by Stralle** [comment]
Thank you @sskorc for your explanation, I was a bit confused so I used a container/parent to select the children, and not the selector on the siblings :)
